describe('local commerce journey', () => {
  it('searches, adds a product, signs in, checks out, and shows the order', () => {
    cy.visit('/products/')
    cy.get('#product-grid').should('contain', 'Strawberry Cloud Cake')
    cy.get('#search').type('strawberry')
    cy.get('#product-grid').should('contain', 'Strawberry Cloud Cake').and('not.contain', 'Butter Croissant')
    cy.contains('#product-grid a', 'Strawberry Cloud Cake').click()
    cy.get('#product-detail').contains(/RM\s*148\.00/).should('be.visible')
    cy.get('#qty').clear().type('1')
    cy.get('#add').click()
    cy.visit('/cart/')
    cy.get('#cart-items').should('contain', 'Strawberry Cloud Cake')
    cy.contains('Continue to checkout').click()
    cy.contains('Sign in to finish checkout').should('be.visible')

    const email = `e2e-${Date.now()}@example.test`
    cy.visit('/register/')
    cy.get('input[name="name"]').type('E2E Baker')
    cy.get('input[name="email"]').type(email)
    cy.get('input[name="password"]').type('e2e-password-123')
    cy.contains('button', 'Create account').click()
    cy.contains('Check your inbox').should('be.visible')
    cy.visit('/login/?next=/checkout/')
    cy.get('input[name="email"]').type(email)
    cy.get('input[name="password"]').type('e2e-password-123')
    cy.contains('button', 'Sign in').click()
    cy.location('pathname').should('eq', '/checkout/')
    cy.get('#order-summary').contains(/RM\s*156\.88/).should('be.visible')
    cy.get('input[name="fullName"]').type('E2E Baker')
    cy.get('input[name="address1"]').type('1 Test Lane')
    cy.get('input[name="city"]').type('Kuala Lumpur')
    cy.get('input[name="postalCode"]').type('50000')
    cy.contains('button', 'Place dummy order').click()
    cy.contains('Order confirmed').should('be.visible')
    cy.contains('View orders').click()
    cy.get('#orders').contains(/RM\s*156\.88/).should('be.visible')
    cy.get('#orders').should('contain', 'confirmed')
  })
})
